import test from 'node:test';
import assert from 'node:assert/strict';
import {defaults,newDay,visibleTasks,timeline,slots,remaining,resume,calendar,validateBackup,weekStats,nextReview} from '../lib/care.ts';
const settings=()=>({...defaults().settings,commuteDate:'2026-10-06',weekdays:[2],segments:[{id:'walk',mode:'walk',start:'08:00',end:'08:10'},{id:'train',mode:'transit',start:'08:10',end:'09:00'},{id:'bike',mode:'bike',start:'09:00',end:'09:10'}]});
test('mode reduction retains completed lower priority tasks and next day is fresh',()=>{let d=newDay();d.tasks[2].done=true;d.mode='minimum';assert.deepEqual(visibleTasks(d).map(t=>t.id),['food','diary']);d.mode='regular';assert.equal(visibleTasks(d).length,3);assert.equal(newDay().tasks.some(t=>t.done),false);});
test('mixed commute schedules only transit, includes short remainder',()=>{const s=settings();const a=slots(s,new Date('2026-10-06T08:00').getTime());assert.equal(a.length,2);assert.equal((a[0].endAt-a[0].startAt)/60000,25);assert.equal((a[1].endAt-a[1].startAt)/60000,20);assert.equal(a[1].short,true);assert.equal(slots(s,new Date('2026-10-07T08:00').getTime()).length,0);});
test('overnight intervals stay ordered and previous day transit remains available',()=>{const s={...settings(),segments:[{id:'a',mode:'walk',start:'23:30',end:'23:45'},{id:'b',mode:'transit',start:'23:45',end:'00:35'},{id:'c',mode:'walk',start:'00:35',end:'00:45'}]};const rows=timeline(s);assert.equal(rows[2].startAt,rows[1].endAt);assert.equal((rows[2].endAt-rows[0].startAt)/60000,75);assert.equal(slots(s,new Date('2026-10-07T00:10').getTime()).length,1);});
test('overlapping intervals are rejected',()=>{const s=settings();s.segments[1].start='08:05';assert.throws(()=>timeline(s),/重叠/);});
test('timer reload uses timestamps, pause does not count down, commute end caps resume',()=>{const t={id:'t',phase:'focus',status:'running',title:'test',duration:10000,remaining:10000,endAt:12000,limitAt:15000};assert.equal(remaining(t,7000),5000);assert.equal(remaining(t,20000),0);const paused={...t,status:'paused',remaining:5000};assert.equal(remaining(paused,8000),5000);assert.equal(remaining(paused,14000),1000);assert.equal(resume(paused,14000).endAt,15000);assert.equal(resume(paused,16000).status,'expired');});
test('calendar is CRLF, Unicode folded, includes recurrence and display alarm',()=>{const ics=calendar(settings(),'commute',new Date('2026-10-06T07:00').getTime());assert.match(ics,/DTSTART:20261006T080000/);assert.match(ics,/DTEND:20261006T091000/);assert.match(ics,/RRULE:FREQ=WEEKLY;BYDAY=TU/);assert.match(ics,/BEGIN:VALARM\r\nTRIGGER:PT0M\r\nACTION:DISPLAY/);assert.ok(ics.split('\r\n').every(line=>Buffer.byteLength(line)<=75));assert.ok(!ics.replaceAll('\r\n','').includes('\n'));});
test('one-off calendar has no recurrence; overnight end increments date',()=>{const s={...settings(),weekdays:[],segments:[{id:'a',mode:'transit',start:'23:30',end:'00:15'}]};const ics=calendar(s,'commute');assert.ok(!ics.includes('RRULE'));assert.match(ics,/DTEND:20261007T001500/);});
test('review recurrence weekly, biweekly and monthly match configured time',()=>{const s=settings();const now=new Date('2026-10-06T10:00').getTime();assert.equal(nextReview(s,now).getDate(),11);assert.match(calendar({...s,reviewFrequency:'biweekly'},'review',now),/INTERVAL=2;BYDAY=SU/);assert.match(calendar({...s,reviewFrequency:'monthly',reviewMonthDay:15},'review',now),/BYMONTHDAY=15/);assert.match(calendar(s,'review',now),/T203000/);});
test('backup validates photos and rejects malformed records without mutation',()=>{const s=defaults();s.diaries.push({id:'a',date:'2026-10-06',mood:'test',energy:3,food:'',activity:'',note:'note',weight:null,photos:[{id:'p',data:'data:image/jpeg;base64,/9j/'}]});assert.deepEqual(validateBackup(JSON.parse(JSON.stringify(s))),s);assert.throws(()=>validateBackup({...s,version:2}));assert.throws(()=>validateBackup({...s,diaries:[{...s.diaries[0],date:'2026-02-30'}]}));assert.throws(()=>validateBackup({...s,diaries:[{...s.diaries[0],photos:[{id:'p',data:'https://external.example/photo'}]}]}));});
test('review statistics exclude future and older records',()=>{const s=defaults();s.days={'2026-10-06':newDay(),'2026-10-07':newDay()};s.days['2026-10-06'].tasks[0].done=true;for(const [date,w] of [['2026-09-01',70],['2026-10-01',65],['2026-10-06',64.5],['2026-10-07',62]])s.diaries.push({id:date,date,mood:'',energy:3,food:'',activity:'',note:'',weight:w,photos:[]});const stats=weekStats(s,new Date('2026-10-06T12:00'));assert.equal(stats.days,2);assert.equal(stats.change,-.5);assert.equal(stats.done,1);assert.equal(stats.total,3);});

test('completed and skipped rounds are excluded from scheduling',()=>{const s=settings(),now=new Date('2026-10-06T08:00').getTime();const list=slots(s,now);assert.equal(slots(s,now,[list[0].id]).length,1);assert.equal(slots(s,now,list.map(x=>x.id)).length,0);});
