import { z } from 'zod';
export const modes = ['regular','busy','minimum'] as const;
export const modeNames = {regular:'常规',busy:'忙碌',minimum:'最低限度'};
const text = z.string().max(10000), id = z.string().min(1).max(100);
export const dateKey = (d = new Date()) => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const date = z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v => dateKey(new Date(v+'T12:00:00')) === v,'日期无效');
const clock = z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/);
const taskSchema = z.object({id,title:z.string().min(1).max(100),category:z.enum(['food','move','relax','diary']),done:z.boolean()});
const segmentSchema = z.object({id,start:clock,end:clock,mode:z.enum(['transit','walk','bike','drive'])}).refine(s=>s.start!==s.end,'起止时间不能相同');
const timerSchema = z.object({id,phase:z.enum(['focus','rest']),status:z.enum(['running','paused','expired']),title:text,slotId:id.optional(),endAt:z.number().finite(),remaining:z.number().min(0).max(86400000),duration:z.number().min(0).max(86400000),limitAt:z.number().finite().nullable()});
const diarySchema=z.object({id,date,mood:text,energy:z.number().int().min(1).max(5),food:text,activity:text,note:text,weight:z.number().min(1).max(1000).nullable(),photos:z.array(z.object({id,data:z.string().max(12000000).regex(/^data:image\/jpeg;base64,[A-Za-z0-9+/=]+$/)})).max(6)});
const settingsSchema=z.object({focus:z.number().int().min(1).max(90),rest:z.number().int().min(1).max(30),commuteDate:date,weekdays:z.array(z.number().int().min(0).max(6)).max(7),segments:z.array(segmentSchema).max(12),reviewFrequency:z.enum(['weekly','biweekly','monthly']),reviewDay:z.number().int().min(0).max(6),reviewMonthDay:z.number().int().min(1).max(28),reviewTime:clock});
export const stateSchema=z.object({version:z.literal(1),revision:z.number().int().nonnegative(),settings:settingsSchema,days:z.record(date,z.object({mode:z.enum(modes),tasks:z.array(taskSchema).max(50)})),diaries:z.array(diarySchema).max(10000),reviews:z.array(z.object({id,date,good:text,hard:text,next:text})).max(10000),sessions:z.array(z.object({id,date,title:text,slotId:id.optional(),status:z.enum(['completed','skipped','ended']),minutes:z.number().nonnegative()})).max(100000),timer:timerSchema.nullable()});
export type State=z.infer<typeof stateSchema>;
export type Settings=State['settings'];
export type Diary=State['diaries'][number];
export type Mode=typeof modes[number];
export type Task=z.infer<typeof taskSchema>;
export type Segment=Settings['segments'][number];
export type TimerState=z.infer<typeof timerSchema>;
export const uid=()=>crypto.randomUUID();
export function defaults():State{return{version:1,revision:0,settings:{focus:25,rest:5,commuteDate:dateKey(),weekdays:[1,2,3,4,5],segments:[],reviewFrequency:'weekly',reviewDay:0,reviewMonthDay:1,reviewTime:'20:30'},days:{},diaries:[],reviews:[],sessions:[],timer:null};}
export function newDay():State['days'][string]{return {mode:'regular',tasks:[{id:'food',category:'food',title:'记录一餐饮食',done:false},{id:'move',category:'move',title:'安排一段轻活动',done:false},{id:'diary',category:'diary',title:'写下一句今日感受',done:false}]};}
export function visibleTasks(day:State['days'][string]){const count={regular:3,busy:2,minimum:1}[day.mode];return day.tasks.filter((t,i)=>t.done || i<count);}
export const transportNames={transit:'地铁 / 公交',walk:'步行',bike:'骑车',drive:'驾驶'};
export function timeline(settings:Settings,base=settings.commuteDate){let offset=0,previous=-1;const rows=settings.segments.map(s=>{let start=new Date(`${base}T${s.start}:00`);start.setDate(start.getDate()+offset);if(start.getTime()<previous){offset++;start.setDate(start.getDate()+1);}let end=new Date(`${dateKey(start)}T${s.end}:00`);if(end<=start)end.setDate(end.getDate()+1);previous=start.getTime();return {...s,startAt:start.getTime(),endAt:end.getTime()};});for(let i=1;i<rows.length;i++)if(rows[i].startAt<rows[i-1].endAt)throw new Error('通勤区间有重叠，请按出发顺序调整。');if(rows.length&&rows.at(-1)!.endAt-rows[0].startAt>86400000)throw new Error('一段通勤请控制在 24 小时内。');return rows;}
export function activeTimeline(s:Settings,now=Date.now()){const today=dateKey(new Date(now));const yesterday=new Date(now);yesterday.setDate(yesterday.getDate()-1);return [dateKey(yesterday),today].flatMap(d=>{if(d<s.commuteDate)return [];if(s.weekdays.length ? !s.weekdays.includes(new Date(d+'T12:00').getDay()): d!==s.commuteDate)return [];return timeline(s,d);}).filter(row=>row.endAt>now);}
export function slots(s:Settings,now=Date.now(),excluded:string[]=[]){return activeTimeline(s,now).flatMap(seg=>{if(seg.mode!=='transit')return [];const result:{id:string;startAt:number;endAt:number;short:boolean}[]=[];let at=seg.startAt;let n=0;while(at<seg.endAt){const left=(seg.endAt-at)/60000;const focus=Math.min(s.focus,left);if(focus<1)break;result.push({id:seg.id+'-'+at,startAt:at,endAt:at+focus*60000,short:focus<s.focus});at+=(focus+s.rest)*60000;if(++n>150)break;}return result.filter(x=>x.endAt>now&&!excluded.includes(x.id));});}
export function remaining(t:TimerState,now=Date.now()){return t.status==='running'?Math.max(0,Math.min(t.endAt,t.limitAt??Infinity)-now):Math.max(0,Math.min(t.remaining,(t.limitAt??Infinity)-now));}
export function resume(t:TimerState,now=Date.now()):TimerState{const endAt=Math.min(now+t.remaining,t.limitAt??Infinity);return{...t,endAt,remaining:Math.max(0,endAt-now),status:endAt<=now?'expired':'running'};}
export function nextReview(s:Settings,now=Date.now()){const d=new Date(now);const [h,m]=s.reviewTime.split(':').map(Number);d.setHours(h,m,0,0);if(s.reviewFrequency==='monthly'){d.setDate(s.reviewMonthDay);if(d.getTime()<=now)d.setMonth(d.getMonth()+1);}else{const delta=(s.reviewDay-d.getDay()+7)%7;d.setDate(d.getDate()+delta);if(d.getTime()<=now)d.setDate(d.getDate()+7);if(s.reviewFrequency==='biweekly'){const anchor=new Date(s.commuteDate+'T12:00');anchor.setDate(anchor.getDate()+(s.reviewDay-anchor.getDay()+7)%7);const weeks=Math.round((Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())-Date.UTC(anchor.getFullYear(),anchor.getMonth(),anchor.getDate()))/604800000);if(Math.abs(weeks)%2===1)d.setDate(d.getDate()+7);}}return d;}
function icsDate(d:Date){return dateKey(d).replaceAll('-','')+'T'+String(d.getHours()).padStart(2,'0')+String(d.getMinutes()).padStart(2,'0')+'00';}
function escapeICS(s:string){return s.replaceAll('\\','\\\\').replaceAll('\n','\\n').replaceAll(';','\\;').replaceAll(',','\\,');}
export function foldICS(line:string){let out='',part='',bytes=0;for(const c of line){const b=new TextEncoder().encode(c).length;if(bytes+b>75){out+=part+'\r\n';part=' ';bytes=1;}part+=c;bytes+=b;}return out+part;}
export function calendar(s:Settings,kind:'commute'|'review',now=Date.now()){let start:Date,end:Date,rule='',title:string;
 if(kind==='commute'){if(!s.segments.length)throw new Error('请先设置通勤区间。');let day=new Date(s.commuteDate+'T12:00');if(s.weekdays.length){while(!s.weekdays.includes(day.getDay()))day.setDate(day.getDate()+1);}const rows=timeline(s,dateKey(day));start=new Date(rows[0].startAt);end=new Date(rows.at(-1)!.endAt);rule=s.weekdays.length?'RRULE:FREQ=WEEKLY;BYDAY='+s.weekdays.map(d=>['SU','MO','TU','WE','TH','FR','SA'][d]).join(','):'';title='通勤轻养 · 出发前看看今天的安排';}
 else{start=nextReview(s,now);end=new Date(start.getTime()+15*60000);rule=s.reviewFrequency==='monthly'?`RRULE:FREQ=MONTHLY;BYMONTHDAY=${s.reviewMonthDay}`:`RRULE:FREQ=WEEKLY;INTERVAL=${s.reviewFrequency==='biweekly'?2:1};BYDAY=${['SU','MO','TU','WE','TH','FR','SA'][s.reviewDay]}`;title='通勤轻养 · 给自己一次温柔复盘';}
 const stamp=new Date(now).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z');return ['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Commute Light Care//ZH','CALSCALE:GREGORIAN','BEGIN:VEVENT',`UID:commute-care-${kind}@local.device`,`DTSTAMP:${stamp}`,`DTSTART:${icsDate(start)}`,`DTEND:${icsDate(end)}`,rule,`SUMMARY:${escapeICS(title)}`,'DESCRIPTION:打开通勤轻养查看安排。修改网页设置后请手动替换旧日历事件。','BEGIN:VALARM','TRIGGER:PT0M','ACTION:DISPLAY',`DESCRIPTION:${escapeICS(title)}`,'END:VALARM','END:VEVENT','END:VCALENDAR'].filter(Boolean).map(foldICS).join('\r\n')+'\r\n';}
export function validateBackup(value:unknown):State{const data=stateSchema.parse(value);timeline(data.settings);const ids=(items:{id:string}[])=>{if(new Set(items.map(x=>x.id)).size!==items.length)throw new Error('备份内存在重复记录。');};ids(data.diaries);ids(data.reviews);ids(data.sessions);Object.values(data.days).forEach(d=>ids(d.tasks));data.diaries.forEach(d=>ids(d.photos));if(data.timer)data.timer={...data.timer,status:'paused',remaining:remaining(data.timer)};return data;}
export function weekStats(data:State,now=new Date()){const end=dateKey(now);const from=new Date(now);from.setDate(from.getDate()-6);const start=dateKey(from);const diaries=data.diaries.filter(d=>d.date>=start&&d.date<=end);const tasks=Object.entries(data.days).filter(([d])=>d>=start&&d<=end).flatMap(([,d])=>visibleTasks(d));const weights=diaries.filter(d=>d.weight!==null).sort((a,b)=>a.date.localeCompare(b.date));return{start,end,days:new Set(diaries.map(d=>d.date)).size,done:tasks.filter(t=>t.done).length,total:tasks.length,weights,change:weights.length>1?Math.round((weights.at(-1)!.weight!-weights[0].weight!)*10)/10:null};}
